### ISSUE TITLE
[Problem?] Line breaks do not follow "Strict line breaks" setting

### ISSUE THREAD

**Issue by emisjerry** [kitschpatrol/yanki-obsidian#10]
Hi Eric,

I've disabled "Strict line breaks" in the Obsidian Editor setting. So the following text will be rendered as three lines in Preview and Reading mode:

```
This is line 1.
This is line 2.
This is line 3.
```

But the result after syncing, these lines will be put in a `<p>`、`</p>`. It will be rendered as ONE line if i preview this card.
![image](https://github.com/user-attachments/assets/7dbca466-79a4-494f-b6a2-6f18301bb52d)

Could you follow the line breaks settings? If turn the setting off, append a `<br>` at the end of each line.
Maybe you'll have better idea to this issue. Thanks.

**Comment by kitschpatrol** [comment]
Thanks, yes for the sake of remaining as Obsidian-agnostic as possible, Yanki has its own Markdown to HTML conversion implementation, which is not (currently) aware of Markdown-related settings elsewhere in Obsidian.

Will fix, but might be a week or two until I have the time.

**Comment by kitschpatrol** [comment]
This should be fixed in the latest release, 1.4.2.
