### ISSUE TITLE
Furigana support

### ISSUE THREAD

**Issue by ilocanojin** [kitschpatrol/yanki-obsidian#12]
Hi. I'm learning Japanese and I'm wondering if there's a way to make furigana show correctly on Anki?

I use the following plugin for my notes and I hope to make it work with Yanki.

https://github.com/steven-kraft/obsidian-markdown-furigana

**Comment by kitschpatrol** [comment]
Hi, thank you for using the plugin and for the request.

I'll look into implementing support for this.

**Comment by kitschpatrol** [comment]
Hi, this is not forgotten, I just haven't had time yet.

It's "next up" in the feature queue.

**Comment by kitschpatrol** [comment]
[DenDen Markdown](https://conv.denshochan.com/markdown#ruby)-style Furigana markup is now supported in Yanki Obsidian version 1.5.0.

For example:

```markdown
{東京|とうきょう}
````

Creates the following markup in your Anki note:

```html
<ruby>東京<rp>(</rp><rt>とうきょう</rt><rp>)</rp></ruby>
```

Rendering as:

<ruby>東京<rp>(</rp><rt>とうきょう</rt><rp>)</rp></ruby>

Note that using Ruby syntax directly is just fine as well, and seems to be supported natively by both Obsidian and Anki.
