### ISSUE TITLE
Support Yanki on Obsidian mobile via AnkiConnectAndroid

### ISSUE THREAD

**Issue by rycue** [kitschpatrol/yanki-obsidian#15]
Hi. Is it possible to use Yanki on Obsidian mobile using this [AnkiConnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid)?

**Comment by kitschpatrol** [comment]
Hi thanks for this idea and for bringing [AnkiConnectAndroid](https://github.com/KamWithK/AnkiconnectAndroid) to my attention — I wasn't aware of it previously.

This could be a nice feature to have, but unfortunately:

1. There's no way to identify a plugin as supporting only specific mobile platforms in the Obsidian community plugin listings. (You only have the [`isDesktopOnly`](https://docs.obsidian.md/Reference/Manifest#Plugin-specific+properties) flag.) This means that the plugin would just seem broken to iOS users.
2. I don't own an Android device to test with.
3. I don't have time to develop and provide support for another platform at the moment.

I would be open to a PR if there's a good solution to item 1 above.

I'll update the readme to mention AnkiConnectAndroid as a note to future selves.
