### ISSUE TITLE
Allow for tags or properties to make a note a flashcard note instead of just folders

### ISSUE THREAD

**Issue by Minoo7** [kitschpatrol/yanki-obsidian#16]
It would be great if there were additional ways to make a flashcard note a flashcard note. For example adding the tag #flashcard or setting a property frontmatter property like flashcard: true. There are cases for me right now where I want a note to be a flashcard but I don't want to move it to a specific folder.

My initial thought was that I could just have the / folder but then all of my notes are interpreted as flashcards, even if they don't have a: --- in them, which is another issue.

Thanks

**Comment by kitschpatrol** [comment]
Hi Vincent, thank you for trying out the plugin.

I can see the appeal of having additional ways to select notes for syncing, but I'm trying to think of how it could work in harmony with the folder-based approach... and I like the fact that the current approach lets you easily create new notes without messing with tags / frontmatter.

There are ways that this could possibly work, and I might revisit it in the future, but I don't have the bandwidth to develop and support this functionality at the moment. 

Maybe [another plugin](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#other-obsidian-anki-plugins) will accommodate your use case.

---

Regarding interpreting all notes in a synced folder as flashcards even in the absence of a `---`, this is working as designed.

Certain note types like "Basic (type in the answer)" and "Cloze" do not require a `---`, and in other cases notes without `---` are interpreted as "Basic" notes that only have a front and are empty on the back. See the [Markdown note types section in the documentation](https://github.com/kitschpatrol/yanki-obsidian?tab=readme-ov-file#markdown-note-types) for a full explanation of how Markdown is mapped to flashcards.
