### ISSUE TITLE
Code snippet error

### ISSUE THREAD

**Issue by jakeoung** [kitschpatrol/yanki-obsidian#2]
First of all, thanks for the amazing plugin!

If I have a markdown file containing

```markline
something
```

There is an error:
shikierror: language 'markline' not found, you may need to load it first

**Comment by kitschpatrol** [comment]
Hi, thanks for trying the plugin.

Yanki doesn't currently support `markline`, which is why you're seeing this error. I will look into adding support.

(I'm assuming you're using the [`obsidian-markline`](https://github.com/hotoo/obsidian-markline) plugin to embed timelines in your notes, correct?)

**Comment by kitschpatrol** [comment]
I've released a new version of the Yanki Obsidian plugin, [`1.0.5`](https://github.com/kitschpatrol/yanki-obsidian/releases/tag/1.0.5), which should prevent the error you're seeing and allow the note to sync to Anki with the code block intact.

However, note that the code block will render as plain monospace text in Anki, not as the interactive timeline you might be used to seeing in Obsidian if you are indeed using the [`obsidian-markline`](https://github.com/hotoo/obsidian-markline) plugin.

I looked into supporting `markline` and rendering timelines in Anki via Yanki, and unfortunately I don't think it's going to be practical to do so given the complexity and interactivity of the HTML `markline` outputs.

When you have a minute, please update your Yanki plugin to the latest [`1.0.5`](https://github.com/kitschpatrol/yanki-obsidian/releases/tag/1.0.5) release, and let me know if it fixes the sync error on your end.

**Comment by jakeoung** [comment]
It has solved the issue! Definitely, I don't want to see the rendering of timeline in anki. I just want to avoid the error :) Thanks for the udpate!

**Comment by kitschpatrol** [comment]
Ok, great!
