### ISSUE TITLE
Convert Obsidian nested tags to Anki tags

### ISSUE THREAD

**Issue by Positron010** [kitschpatrol/yanki-obsidian#20]
Hi, and thanks for the plugin.
Currently, Obsidian nested tags, e.g. `tag1/tag2/tag3` are synced to Anki as they are. I propose to convert Obsidian nested tags to Anki tags, meaning that `tag1/tag2/tag3` is converted in Anki to `tag1::tag2::tag3` to maintain the nested hierarchy.

Thanks

**Comment by kitschpatrol** [comment]
Thanks, good idea. Will implement this for the next release, probably in a week or two.

**Comment by kitschpatrol** [comment]
Pardon the delay on this. Still planning to implement, but I can't guarantee a timeline at the moment.
