### ISSUE TITLE
Anki strikethrough hidden, and displayed as a gradient highlight when the mouse hovers over, in order to achieve aesthetic purposes.

### ISSUE THREAD

**Issue by zhuzhige123** [kitschpatrol/yanki-obsidian#26]
- Hello。I don't know where this modification suggestion should be placed, it's my first time uploading personal modification methods.
If there is any offense, I apologize and please move or delete it.
- This is all achieved through Obsidian CSS, and it does not affect Yanki.
- Explain that this CSS snippet is a supplementary method for beautifying the strikethrough mark in Yanki, because I think the display effect of the strikethrough on the text is not good-looking. The method of hiding and displaying synchronization with Yanki to Anki for memory is not contradictory, this is justOn a temporary basis. I really like the synchronization effect of Yanki, while Anki's memory planning is more scientific and more long-lasting.
- I am used in combination.
---
- Two CSS files, one does not hide the text, and the other displays on hover.
At the same time, the spacing between highlighted texts has been increased to avoid displaying them together.
[Solution for Strikethrough Gradient Highlight Display.zip](https://github.com/user-attachments/files/17815820/Solution.for.Strikethrough.Gradient.Highlight.Display.zip)

---

![image](https://github.com/user-attachments/assets/9d0d4582-c0c7-41bd-bb7f-8e691e6f0149)

![image](https://github.com/user-attachments/assets/dfc14c71-1296-4f4f-bb14-d5cded3e2a31)
![image](https://github.com/user-attachments/assets/10121539-06eb-48e8-b193-2b1fdf7e49fe)
![image](https://github.com/user-attachments/assets/d48007bc-29be-4477-89af-b7f8dcf43436)

**Comment by kitschpatrol** [comment]
This makes sense, thanks for sharing. I'm glad you found a solution with CSS.

I'll close this issue since it's not an ongoing problem, but it will remain visible in the archives.

Good luck with your studies.
