### ISSUE TITLE
Assets not syncing (在anki中有的同步文件夹内的图片全部不显示)

### ISSUE THREAD

**Issue by zhuzhige123** [kitschpatrol/yanki-obsidian#27]
你好。

-我尝试移动所在文件夹。 删除特殊标记符号，标签等，但都未成功找到错误在哪里。

- 打包了其中一个不显示图片的markdown文档，包含图片。

- 在obsidian中显示，anki中就完全不显示。

- yanki同步提示为成功。

---

English：
I tried to move the folder I am in. I deleted special marker symbols, tags, etc., but I have not been able to find where the error is.
- Packaged a Markdown document that doesn't display images, which contains images.
- It can be displayed in Obsidian, but it is completely not displayed in Anki.
- Yanki synchronization prompt is successful.
---

[新建文件夹 (2).zip](https://github.com/user-attachments/files/17819657/2.zip)
![Pasted image 20241120014613](https://github.com/user-attachments/assets/b17a7423-a901-447b-aa05-03c0715feab3)
![Pasted image 20241120015131](https://github.com/user-attachments/assets/b82d9a5d-5ba1-4e7e-ae49-d4793ba35f8d)
![Pasted image 20241120014929](https://github.com/user-attachments
![Pasted image 20241120014854](https://github.com/user-attachments/assets/18f5f74c-5f6f-4bc6-bd79-9ecfcc594948)
/assets/7e274241-8f7a-4d40-9ac6-d7179a42381b)

**Comment by kitschpatrol** [comment]
Hi, thanks for providing an example. I'm not sure I completely understand what you want to happen, but it seems like you just have a lot of syntax errors in your Markdown.

After correcting the errors, and the resulting note syncs to Anki along with all 19 embedded images:

![Screenshot 2024-11-19 at 20 53 49 of Anki - Browse (1 of 33 cards selected)@2x](https://github.com/user-attachments/assets/637e7f38-7776-4d13-9e9f-44905256ec58)

Here's the corrected markdown:

```markdown
---
excalidraw-plugin: '[详解电解质对人体的影响.excalidraw](详解电解质对人体的影响.excalidraw "wikilink")'
tags:
  - 《刻意练习》
难度系数:
  - ⭐⭐
noteId: 1732038438855
---

[冠状动脉粥样硬化性心脏病病人的护理](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4)

[hszg_jjb_20_48.mp4](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4)

- [ ] 第六节-冠状动脉粥样硬化性心脏病病人的护理 [../日记/2024-01-01.md](../日记/2024-01-01.md "wikilink")#todo 

![Pasted image 20240101130355.png](Pasted%20image%2020240101130355.png) 
![Pasted image 20240101130530.png](Pasted%20image%2020240101130530.png)

![Pasted image 20240101130754.png](Pasted%20image%2020240101130754.png)

[04:48](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4#t=288.84274)

![Pasted image 20240101131009.png](Pasted%20image%2020240101131009.png)

[06:31](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4#t=391.23255)

[10:54](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4#t=654.341478)

![Pasted image 20240101131332.png](Pasted%20image%2020240101131332.png)

[11:51](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4#t=711.610285)

![Pasted image 20240101131411.png](Pasted%20image%2020240101131411.png)
舌下含服，毛细血管直接入血

[14:31](http://v.zaixue100.com/YZX_video/8379be8231a24973a60fd82d4542223e/fd_1559010338336/hszg_jjb_20_47.mp4#t=871.777549)

![Pasted image 20240101131553.png](Pasted%20image%2020240101131553.png)

冠状动脉粥样硬化心脏病

[00:53](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=53.294782)

![Pasted image 20240101132034.png](Pasted%20image%2020240101132034.png)

[04:06](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=246.299438)

![Pasted image 20240101132116.png](Pasted%20image%2020240101132116.png)

![Pasted image 20240101132500.png](Pasted%20image%2020240101132500.png)

[09:36](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=576.421502)

![Pasted image 20240101132704.png](Pasted%20image%2020240101132704.png)

[09:55](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=595.39131)

![Pasted image 20240101132714.png](Pasted%20image%2020240101132714.png)![Pasted image 20240101132922.png](Pasted%20image%2020240101132922.png)

[12:47](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=767.988194)

![Pasted image 20240101132942.png](Pasted%20image%2020240101132942.png)
肌红蛋白在心肌，
肌钙蛋白，特异性

[16:33](http://v.zaixue100.com/YZX_video/05823b43e956460f8e84baaf1813417d/fd_1559010338336/hszg_jjb_20_48.mp4#t=993.74753)

![Pasted image 20240101133228.png](Pasted%20image%2020240101133228.png)
利多卡因

    治疗心率失常，是防治急性心肌梗死及各种心脏病并发快速室性心律失常药物，是急性心肌梗死的室性早搏，室性心动过速及室性震颤的首选药

![Pasted image 20240101133504.png](Pasted%20image%2020240101133504.png)
![Pasted image 20240101133531.png](Pasted%20image%2020240101133531.png)
![Pasted image 20240101133800.png](Pasted%20image%2020240101133800.png)
![Pasted image 20240101133856.png](Pasted%20image%2020240101133856.png)

```

**Comment by zhuzhige123** [comment]
@kitschpatrol 
Hello, can you circle with a pen where the grammar error is? I can't find it.。

**Comment by kitschpatrol** [comment]
There were a bunch of changes, here's the diff:

https://gist.github.com/kitschpatrol/7a408edb3113a52069a4a1d3ba619fc1/revisions?source=1#diff-829e869f216c66f25c7ed0d210dc222d73373444bf15a3a55496530d3cd2ff79

You had a bunch of `\` characters, which acts as an escape character in Markdown, some unclosed and unneeded `[` brackets, and some `<` / `>` characters that weren't making sense.

Obsidian will do its best to render broken Markdown, but it's going to create issues elsewhere.

There are Obsidian plugins like [Linter](https://obsidian.md/plugins?id=obsidian-linter) that can help spot syntax errors and ensure consistent Markdown formatting.

**Comment by zhuzhige123** [comment]
@kitschpatrol 

Verified, it is indeed caused by this issue.

Thank you very much
