### ISSUE TITLE
Sync fails when brackets are present in the absolute vault path

### ISSUE THREAD

**Issue by fislysandi** [kitschpatrol/yanki-obsidian#28]
i was moving into a new foldering system, and ia noticed that 
Steps to repeat the bug
1. open the obisidan vault manager
2. move the vault to a new folder (for an example "[01] fislysandi"
3. get a sync error.

idk why it happens, hopefully it will be fixed.

so far im really enjoying this plugin because it allows me to write anki cards within the comfort of obsidian.

**Comment by kitschpatrol** [comment]
Thanks for reporting this issue!

I was able to reproduce the sync errors, and they're specifically related to the brackets in the folder name.

If you move the vault to a folder without special characters like `[` and `]` in it, it will sync successfully.

I'll have to look into where exactly this is happening. If you need an immediate work-around, remove the brackets from the folder name.

**Comment by kitschpatrol** [comment]
This should be fixed in v1.6.1.

Please feel free to comment on this issue if you're still seeing the error.
